name: (PROD) S3 Deploy and CF Invalidation
on:
  push:
    branches:
      - main
jobs:
  run:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: prod
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      REACT_APP_QUICKNODE_RPC_URL_MAINNET: ${{ secrets.REACT_APP_QUICKNODE_RPC_URL_MAINNET }}
      REACT_APP_QUICKNODE_RPC_URL_ARBITRUM: ${{ secrets.REACT_APP_QUICKNODE_RPC_URL_ARBITRUM }}
      REACT_APP_ENV: ${{ vars.REACT_APP_ENV }}
    steps:
        - uses: actions/checkout@v3

        - name: Install dependencies
          run: yarn

        - name: Build
          run: yarn build

        - name: Deploy
          uses: Propy/s3-deploy@v3
          with:
            folder: build
            bucket: ${{ secrets.S3_BUCKET }}
            bucket-region: ${{ secrets.S3_BUCKET_REGION }}
            dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
            invalidation: "/*"
            delete-removed: true
            no-cache: true
            private: true
            filesToInclude: ".*/*,*/*,**"